name: Trigger Netlify Build Every 48h

on:
  schedule:
    - cron: '0 7 */2 * *'  # Toutes les 48h
  workflow_dispatch:        # Permet de le déclencher manuellement si besoin

jobs:
  ping-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          curl -X POST ${{ secrets.NETLIFY_BUILD_HOOK }}
